stages:
  clean_data:
    cmd: python src/data/clean.py ./data/raw/itineraries_random_2M.csv ./data/interim/flights.csv
    deps:
      - ./src/data/clean.py
      - ./data/raw/itineraries_random_2M.csv
    outs:
      - ./data/interim/flights.csv

  prepare_airport_coords:
    cmd: python src/data/prepare_airport_coords.py ./data/external/GlobalAirportDatabase.txt ./data/external/gadb_declatlon.csv ./data/interim/airport_coords.csv
    deps:
      - src/data/prepare_airport_coords.py
      - ./data/external/GlobalAirportDatabase.txt
      - ./data/external/gadb_declatlon.csv
    outs:
      - ./data/interim/airport_coords.csv

  build_features:
    cmd: python src/features/build_features.py ./data/interim/flights.csv ./data/interim/airport_coords.csv ./data/processed/flights.csv
    deps:
      - src/features/build_features.py
      - ./data/interim/flights.csv
      - ./data/interim/airport_coords.csv
    outs:
      - ./data/processed/flights.csv

  train_test_split:
    cmd: python src/models/train_test_split.py ./data/processed/flights.csv ./data/processed/train.csv ./data/processed/test.csv
    deps:
      - ./src/models/train_test_split.py
      - ./data/processed/flights.csv
    outs:
      - ./data/processed/train.csv
      - ./data/processed/test.csv

  train:
    cmd: python src/models/train_model.py ./data/processed/train.csv ./data/processed/test.csv ./models/model.cbm
    deps:
      - src/models/train_model.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/model.cbm

  evaluate:
    cmd: python src/models/evaluate.py ./models/model.cbm ./data/processed/test.csv ./reports/score.csv
    deps:
      - src/models/evaluate.py
      - ./models/model.cbm
      - ./data/processed/test.csv
    outs:
      - ./reports/score.csv
